---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
As kingfishers catch fire, dragonflies draw   flame;  
  
As tumbled over rim in roundy wells  
  
Stones ring; like each tucked string tells,   each hung bell’s  
  
Bow swung finds tongue to fling out broad its   name;  
  
Each mortal thing does one thing and the same:  
  
Deals out that being indoors each one dwells;  
  
Selves — goes itself; myself it speaks and   spells,  
  
Crying Whát I dó is me: for that I came.  
  
I say móre: the just man justices;  
  
Keeps grace: thát keeps all his goings graces;  
   
Acts in God’s eye what in God’s eye he is —  
  
Chríst — for Christ plays in ten thousand   places,  
  
Lovely in limbs, and lovely in eyes not his  
  
To the Father through the features of men’s   faces.  
